### ISSUE TITLE
Add a Scroll To Top Button in Pages for Better Experience.

### ISSUE THREAD

**Issue by devpenzil** [web2feel/frontend-interviews#2]
If a user on the bottom of the page its really hard to go back to top.
The smooth scroll feature also decrease the speed .
So add a **Scroll to top button** in all pages.

**Comment by web2feel** [comment]
A scroll-to-top button is added now for an improved scrolling experience.

**Comment by devpenzil** [comment]
But there is a problem
make the button fixed.
Now user need to scroll to bottom to see the button.
Thats not better.
Make it fixed on the bottom.
[Refer This](https://codepen.io/matthewcain/pen/ZepbeR)
